# Abstract

Access to contraceptive options is fundamental to empower women to take charge of their own health, enabling them to make informed decisions about family planning. But barriers to access to contraceptives still exists in most developing countries. In this study, we built a classification model using the SVC classifier algorithm which can help predict the use/or no use contraceptives by women based on their demographic and socio-economic characteristics. The data used in our project was a subset of 1987 National Indonesia Contraceptive Prevalence Survey. 1473 samples were selected from the original samples and all  samples are married women who were either not pregnant or do not know if they were at the time of interview.

When evaluating the training set, the RBF SVC classifier showed the best cross-validation score. Similarly, when evaluating the test set, the overall accuracy of the model was 74% and the area under the curve (AUC) was of 78%. Therefore, it can be conducted that RMB SVC is the most suitable model for this classification problem given that the data-set provided. However given that this model had moderate amount of false predictions for the no-use of contraceptive method, further work to improve model prediction was needed before we could put this model in the real world.