
# Introduction

Family planning offers immediate health benefits, potential non-health benefits that encompass expanded education opportunities and empowerment for women as well as economic advancement. Consequently, the proportion of women of reproductive age who are in need for modern contraceptive methods has increased gradually from 73.6 percent in 2000 to 76.8 percent in 2020 [@un2020fp]. Reasons for the slow growth may arise from lack of access to services, poor quality of available services, gender barriers and personal bias against some methods. These limitations are not addressed in some regions due to their cultural/traditional beliefs, financial background, religious influence, etc. 

In last two decades, decision tree-based and multivariate regression-based prediction models have received some attention in the study of family planning, but it generally exhibit modest predictive performance, especially for certain large and complicated datasets [@Lim_acomparison]. Machine learning (ML) such as SVC can improve the performance by exploiting large data repositories to identify novel predictors and non-linear interactions between them.

In this study, we conducted a prediction model research based on a specific background in Indonesia. The objective is to predict whether the contraceptive method is used by Indonesian women based on their demographic and socio-economic factors. In 1991, a dataset were taken from the 1987 National Indonesia Contraceptive Prevalence Survey and a cohort of 1473 samples were selected. 