# Conclusion

The process intended to predict the use of contraceptives in married women based on their socio-economic and demographic information. In the process, 4 different models were tried. In our study, the best model RMB SVC performed well given the size of the data-set  with an accuracy of $74\%$ , `recall` of $90\%$, `precision` of $73\%$ , `f1_score` of $80\%$ and `AUC` $78\%$. The precision indicates, that out of all predicted positives, how many are positive, i.e. out of 100 predicted positive samples, 73 were using the contraceptives. High Recall indicated, out of total positives how many were predicted positive A high recall showed that our model could identify most of them correctly. These results were in line with the validation scores outlined previously. The result of high `recall value` of $90\%$ also indicated that `False Negatives` were very low and showed an appreciable f1_score of 0.8.

Since the size of the data set was significantly small (only 1473), the accuracy rate of the models developed could be considered low to represent the entire county (Indonesia). Also, this dataset could be a biased one, considering its small size of it. As a well-known limitation of the supervised machine learning is that it requires a large number of data to achieve a reasonably accurate model. Therefore, if a larger data set is available for this exercise, then a more accurate model could have been developed. In opposed to supervised machine learning, deep learning would have been a better approach for this kind of problem with limited data sets. There is room to improve the model in future by considering more parameters and more ensemble methods during the hyperparameter tuning process.
