---
title: "Study of contraceptive method prediction model in Indonesia"
author: "Harry Chan"
date: "updated: `r Sys.Date()`"
always_allow_html: true
output: 
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: true
  bookdown::html_document2:
    fig_caption: yes
    number_sections: yes
    toc: true
bibliography: 
  cmp_refs.bib
---

```{python setup_py, include=FALSE}
import pandas as pd
```

```{r setup_r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
```


```{r persona, child="00_Persona.Rmd"}
```

## Exercise 2: Write your report
The Github repo: https://github.com/harryyikhchan/contraceptive_method_predictor \
The Online PDF Report: https://github.com/harryyikhchan/contraceptive_method_predictor/blob/main/doc/contraceptive_method_predictor_report.pdf

```{r summary, child="01_Summary.Rmd"}
```

```{r intro, child="02_Intro.Rmd"}
```

```{r methods, child ="03_Methods.Rmd"}
```

```{r results, child="04_Results.Rmd"}
```

```{r conclusion, child="05_Conclusion.Rmd"}
```

```{r acknowledgment, child="06_Acknowledgment.Rmd"}
```

# References